import type { Metadata } from "next";
import "./globals.css";
import { AppSidebar } from "@/components/sidebar/AppSidebar";
import { SidebarProvider } from "@/components/ui/sidebar";
import { SidebarMenu } from "@/components/sidebar/SidebarMenu";

export const metadata: Metadata = {
  title: "Todo-Webapp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="de">
      <body className="flex min-h-screen bg-gray-50 dark:bg-zinc-900">
        <SidebarProvider>
          <AppSidebar />
          <main className="flex-1 px-4 sm:px-6 lg:px-8 py-6">
            <SidebarMenu />
            
            {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
